### ISSUE TITLE
The validation of fast travel between consecutive stops not happening

### ISSUE THREAD

**Issue by LuisDiezLaso** [MobilityData/gtfs-validator#1167]
## **Bug report** 

I´m checking feeds that are supposed to throw the warning "Too fast travel between consecutive stops"(the travel speed between some stops is over 1000 km/h in the report generated by the [old feed validator](https://github.com/google/transitfeed)).

**Describe the bug**
Not throwing "too fast travel between consecutive stops" warning  when it should be. 

**How we reproduce the bug**
Tested with the [latest jar produced of the master branch](https://github.com/MobilityData/gtfs-validator/actions/runs/2379815929)
Steps to reproduce the behaviour:
1. Execute the jar for this feed: 
[Gtfs-20220525-0647-.zip](https://github.com/MobilityData/gtfs-validator/files/8770705/Gtfs-20220525-0647-.zip)

**Expected behaviour**
As produced in this report from the old validator, there should be warnings of the type "too fast travel": 
[transitfeed-validation-results.zip](https://github.com/MobilityData/gtfs-validator/files/8770792/transitfeed-validation-results.zip)

**Observed behaviour**
There is 0 warnings of that type (this is the report that i get when executing the jar):
[report.zip](https://github.com/MobilityData/gtfs-validator/files/8770814/report.zip)

**Environment versions**
- validator version: [latest jar produced of the master branch](https://github.com/MobilityData/gtfs-validator/actions/runs/2379815929)
- Java version: java 11.0.15 2022-04-19 LTS
- OS versions: Windows 10

**Comment by maximearmstrong** [comment]
Thank you for reporting this bug @LuisDiezLaso! 

Currently, this is "normal" behavior - we don't run any validation rules involving multiple files if at least one file is unparsable. In the example you provided, `agency.txt` is unparsable, so the rule throwing the [fast_travel_between_consecutive_stops](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#fast_travel_between_consecutive_stops) notice is not checked.

We are aware that this is not sustainable in the long run, so we are planing on modifying the behavior so that it will only skip a validation rule if one of the files required to check it is unparsable.

Let's keep this issue open, which will be fixed with the implementation of the new behavior.
cc @isabelle-dr

**Comment by isabelle-dr** [comment]
@davidgamez this might be the same problem as the one you found in #1308

**Comment by isabelle-dr** [comment]
Closing, this issue is replaced by https://github.com/MobilityData/gtfs-validator/issues/1484
