### ISSUE TITLE
False negative "errors" returned in valdation

### ISSUE THREAD

**Issue by fitzgibbon19** [MobilityData/gtfs-validator#1235]
I recently used the MobilityData GTFS validator and received 269 “Errors” for decreasing_or_equal_time_distance. At BART we have a train route that comes into a station, reverses and then continues its route to its final destination.  So the train is arriving and departing from the same stop_id in the route.  It dwells at the station for two minutes before reversing direction.  Why is this type of error included in the validation report for BART, a Metro system?  So from stop sequence 0 to 1 the train arrives and reverses to stop sequence 2. And in the opposite direction the train in stop sequence 25 to 26 arrives, then reverses to stop sequence 27.  Where stop sequence 0 and 27 are the same place (end of line). Since there is no distance traveled when the train arrives and reverses from the same station, this is normal. Here is the [GoogleDrive link](https://drive.google.com/file/d/1BDpTDUxZqTT3_iVUr7qXTjzP-BzUmTZw/view?usp=sharing) to what the train is doing.## **Bug report** 

**Describe the bug**
decreasing_or_equal_time_distance should not return an error on a Metro type system like BART.

**How we reproduce the bug**
Steps to reproduce the behaviour:
Run a validation procedure.

**Expected behaviour**
no errors returned for decreasing_or_equal_time_distance

**Observed behaviour**
returned errors for decreasing_or_equal_time_distance

**Screenshots:** 
[GoogleDrive link]: (https://drive.google.com/file/d/1BDpTDUxZqTT3_iVUr7qXTjzP-BzUmTZw/view?usp=sharing)

**Environment versions**
- validator version: 
- Java version: 
- OS versions: Windows 10

**Comment by fitzgibbon19** [comment]
[2022_09_12_r6.zip](https://github.com/MobilityData/gtfs-validator/files/9303563/2022_09_12_r6.zip)

**Comment by isabelle-dr** [comment]
Hello @fitzgibbon19, thank you for opening this issue!
This issue will be prioritized in the next release cycles.

**Comment by KClough** [comment]
@isabelle-dr I'm not sure how to resolve this issue other than disabling this rule.

**Comment by isabelle-dr** [comment]
I've downloaded BART's GTFS, here is what the data looks like for what is described above by @fitzgibbon19:

| trip_id | arrival_time | departure_time | stop_id | stop_sequence | shape_dist_traveled |
|---------|--------------|----------------|---------|---------------|---------------------|
| 1401757 |      7:50:00 |        7:50:00 | MLBR    |             0 |                   0 |
| 1401757 |      7:54:00 |        7:54:00 | SFIA    |             1 |                8825 |
| 1401757 |      7:56:00 |        7:56:00 | SFIA    |             2 |                8825 |
| 1401757 |      8:00:00 |        8:00:00 | SBRN    |             3 |               20492 |
| 1401757 |      8:03:00 |        8:03:00 | SSAN    |             4 |               33338 |

@KClough I think this rule has the correct behavior, it is validating:
> Values used for shape_dist_traveled must increase along with stop_sequence; they must not be used to show reverse travel along a route.

We shouldn't disable it because in many cases, this could be unintentional. I wonder if the GTFS should be designed differently.

**Comment by isabelle-dr** [comment]
@fitzgibbon19, is there a particular reason why you need to define two distinct stop_time records for the stops that have the same `shape_dist_traveled`? Could you merge them?
If we take the sample example above, could you have the following in your GTFS?

| trip_id | arrival_time | departure_time | stop_id | stop_sequence | shape_dist_traveled |
|---------|--------------|----------------|---------|---------------|---------------------|
| 1401757 |      7:50:00 |        7:50:00 | MLBR    |             0 |                   0 |
| 1401757 |      7:54:00 |        7:54:00 | SFIA    |             1 |                8825 |
| 1401757 |      8:00:00 |        8:00:00 | SBRN    |             2 |               20492 |
| 1401757 |      8:03:00 |        8:03:00 | SSAN    |             3 |               33338 |

**Comment by isabelle-dr** [comment]
After discussing with the community, I am going to close this issue because it looks like a true positive, and the two `stop_time` records generating this issue should be merged into one.
