### ISSUE TITLE
[REQUEST] Implement Duplicate column (CSV rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#129]
**Is your feature request related to a problem? Please describe.**
Duplicate column is a CSV rule implemented in Google Python validator and featured in Google Type Error as TYPE_CSV_DUPLICATE_COLUMN_NAME.

**Describe the solution you'd like**
A column must not be duplicated in a GTFS file.

**Describe alternatives you've considered**
**Additional context**
Line 22 in Error support priority https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by dudebrains01** [comment]
The validator should flag duplicated columns within a single file. For example:
**stops.txt**
`stop_id,stop_code,stop_name,stop_lat,stop_lon,location_type,stop_id`

In this case, the second `stop_id` column should not exist and should be flagged as **ERROR** because the columns could have non-identical data (e.g. the first `stop_id` column = `s_1` but the second one on the same line = `29`.

However, many column names are intentionally duplicated between different files (e.g. `trip_id` in `trips.txt`, `stop_times.txt` and `frequencies.txt`. This is **not an error**
