### ISSUE TITLE
[REQUEST] Implement overlapping Stop times in Block trips (GTFS rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#132]
**Is your feature request related to a problem? Please describe.**
Stop times should not be overlapping in Block trips. This is a GTFS rule implemented in Google Python validator and featured in Google Type Error as TYPE_BLOCK_TRIPS_WITH_OVERLAPPING_STOP_TIMES.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies trips in a block. Verifies that a trip does not overlap with another one (same stop time for a stop).

**Describe alternatives you've considered**

**Additional context**
Line 39 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by barbeau** [comment]
@lionel-nj Looks like these are the Python unit tests for this rule, which match the interpretation we discussed:
https://github.com/google/transitfeed/blob/1c7f8c03612ac5c9c2b3f9a4cac6c229a04376b9/tests/transitfeed/testschedule.py#L62

One additional item to check, though, before calling it an error, is to make sure that the trips are assigned to the same service_id. You can see these checks in the Python tests.

**Comment by lionel-nj** [comment]
Thank you. Looking at these tests it seems that an error is raised whether trips belong to the same service_id or not. @barbeau 

https://github.com/google/transitfeed/blob/1c7f8c03612ac5c9c2b3f9a4cac6c229a04376b9/tests/transitfeed/testschedule.py#L129

https://github.com/google/transitfeed/blob/1c7f8c03612ac5c9c2b3f9a4cac6c229a04376b9/tests/transitfeed/testschedule.py#L152

From my understanding the following situations would generate a notice: 

| routeId | tripId | serviceId | blockId | first stop time | last stop time |
|---------|--------|-----------|---------|-----------------|----------------|
| 0       | 2      | **a**         | 5       | 07:00           | 10:00          |
| 0       | 5      | **b**         | 5       | _08:45_           | _11:20_          |
| 0       | 8      | **c**         | 5       | 11:40           | 13:50          |

| routeId | tripId | serviceId | blockId | first stop time | last stop time |
|---------|--------|-----------|---------|-----------------|----------------|
| 0       | 2      | **a**         | 5       | 07:00           | 10:00          |
| 0       | 5      | **a**         | 5       | _08:45_           | _11:20_          
| 0       | 8      | **a**         | 5       | 11:40           | 13:50          |

**Comment by barbeau** [comment]
@lionel-nj Sorry, yes, you're right - I should have mentioned that if the service_ids are different, but the services still overlap the same period of time, that's still an error. So if in the above example service_ids `a`, `b`, and `c` are running on January 1st, that's an error.

If the service dates don't overlap, though, then that's fine. So if in the above example service_ids `a` and `c` are running on January 1st only, and `b` is running on January 2nd only, then this is fine (no error).

This 2nd test case for non-overlapping service periods that doesn't throw an error is here in Python:
https://github.com/google/transitfeed/blob/1c7f8c03612ac5c9c2b3f9a4cac6c229a04376b9/tests/transitfeed/testschedule.py#L195

This part of the rule is trickier to implement because you need to interpret both the data in calendar.txt and calendar_dates.txt to understand on what days the service is running.

**Comment by lionel-nj** [comment]
Oh, true! - I see, that does help a lot!
