### ISSUE TITLE
Jitpack for v4.1.0 is broken

### ISSUE THREAD

**Issue by esuomi** [MobilityData/gtfs-validator#1473]
### Describe the bug

See https://jitpack.io/com/github/MobilityData/gtfs-validator/v4.1.0/build.log

Looking at Jitpack's logs, the two main issues are missing documentation for various params and return values and no test artifacts, which together cause the build to fail in such way that nothing is published.

### Steps/Code to Reproduce

 - Click "Get It" on https://jitpack.io/#MobilityData/gtfs-validator for v4.1.0
 - Wait for ages
 - build is broken

### Expected Results

Working build so that I could use gtfs-validator's latest&greatest as Maven dependency.

### Actual Results

No artifact available.

### Validator version

4.1.0

### Operating system

unrelated

**Comment by miles-grant-ibigroup** [comment]
We are facing the same issue, and are also unable to upgrade the package version as a result

**Comment by jcpitre** [comment]
Removed the failed build on jitpack (https://jitpack.io/#MobilityData/gtfs-validator) then did a build on a local test project and jitback rebuilt fine. It should now be available.

As to why it failed before and not now, I have some theories:

- I suspect the problem comes from https://github.com/freefair/gradle-plugins/issues/640. One of the logs for the failed build said: 

> Execution failed for task ':aggregateJavadocJar'.
> Could not add file '/home/jitpack/build/build/docs/aggregateJavadoc/gtfs-validator-4.1.0-javadoc.jar' to ZIP '/home/jitpack/build/build/docs/aggregateJavadoc/gtfs-validator-4.1.0-javadoc.jar'.

i.e. it was trying to add a jar file to itself. This fits with the bug.

- There was a change done in freefair that could have solved the problem, although I am not sure it affected the version we use: https://github.com/freefair/gradle-plugins/commit/1ac0180260d6781c1cd7bc15380ad230b4e5ef3e

- Another possibility is that jitpack changed something in the way they build. In particular it seems that the freefair bug occurs on some linux distros, but not others. Maybe they changed the distro they use for building? Or some other change on their end.

- on the gtfs-validator side, it's building from v4.1.0 tag, so there was no change that could explain why it was broken but not anymore.

**Comment by jcpitre** [comment]
For reference I attached the log of the failed build here, since it was overwritten when the new successful build was done.
[jitpackProblem.txt](https://github.com/MobilityData/gtfs-validator/files/12685041/jitpackProblem.txt)
