### ISSUE TITLE
[REQUEST] Implement route short name and route long name difference verification (GTFS rule)

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#150]
**Is your feature request related to a problem? Please describe.**
Route short name should be different and not contained in route long name. This is a GTFS rule implemented in Google Python validator and featured in Google Type Error as TYPE_ROUTE_SHORT_NAME_EQUALS_LONG_NAME and TYPE_ROUTE_SHORT_NAME_IS_CONTAINED_IN_LONG_NAME.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies if route_short_name is not the same nor contained in route_long_name.

**Describe alternatives you've considered**

**Additional context**
Line 77 and 78 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by barbeau** [comment]
This is another rule that's a bit different from the spec. The spec doesn't say that these two fields MUST be different:
http://gtfs.org/reference/static#routestxt

However, the best practices:
http://gtfs.org/best-practices/#routestxt

...do say:

>route_long_name should not contain the route_short_name.

So we'll need to again consider if we should propose changing the spec to require the names being different, or if this should be a configurable rule too for error vs warning.

**Comment by timMillet** [comment]
If `route.route_short_name` and `route.route_long_name` are exactly the same, it should be an error. The spec allows providing only one of them, so no need to repeat it twice.

If the `route.route_short_name` is contained within the `route.route_long_name`, it should be a warning for now. But I think it's worth changing the spec to adopt that rule from the best practices; so that it will be an error in the future.

On the side: I would also promote to adopt in the spec one other rule, pretty the same, from the best practices:
> Do not provide route names (matching route_short_name and route_long_name) in the trip_headsign or stop_headsign fields.

**Comment by barbeau** [comment]
@timMillet Should we also propose in GTFS spec to add that `route.route_short_name` and `route.route_long_name` cannot be the same? AFAIK that currently isn't in the spec, but seems like it should be.

**Comment by maximearmstrong** [comment]
Rule implemented in PR #217
