### ISSUE TITLE
In the validator report, links towards rules file does not display the rule directly

### ISSUE THREAD

**Issue by jcpitre** [MobilityData/gtfs-validator#1608]
### Describe the bug

In the report, there is a direct link to the rule in the notice. For example:
![image](https://github.com/MobilityData/gtfs-validator/assets/106176106/3be002f3-3301-4192-a5d7-a3fd20d85a6e)

This link points to 
`https://gtfs-validator.mobilitydata.org/rules.html#unknown_column`
But in the rules.md the anchors are like this:
`https://gtfs-validator.mobilitydata.org/rules.html#unknown_column-rule`
with a suffix of `-rule`.

### Steps/Code to Reproduce

- Generate a validation report.
- Click on one of the link to the rule.

### Expected Results

After pressing the link, the rules file should be displayed directly on the description of the rule.

### Actual Results

The top of the rules file is displayed, ie not the specific rule

### Validator version

4.2.0

### Operating system

irrelevant

**Comment by bradyhunsaker** [comment]
Issue #1626 appears to be a duplicate. I'll comment here because this issue is older.

Multiple anchors can be used for each rule in the documentation, while reports can only have a single link. Given that there are lots of existing reports and that the links without -rule are clear, it seems reasonable to add them as additional anchors to the documentation. The owners of the project should make a decision on that. Maybe there is an anchor collision or something that argues against that?

If we want to change the validator reports, the place the links are created is here:
https://github.com/MobilityData/gtfs-validator/blob/3d5ef6f31839f74fff3338c8a8d9869df88cc7c0/main/src/main/resources/report.html#L334

It would be straightforward to add -rule at that point. That feels a little hacky, but I don't think it makes sense to add links to the data structure that they are generated from (noticesByCode), since the keys there already make better sense without the -rule suffix.

**Comment by jcpitre** [comment]
@bradyhunsaker Thanks for looking into that!
It seems to me that adding the -rule to the referred anchors in the html file is acceptable. It does not feel hacky to me. After all the anchor _does_ relate to a rule, so having a -rule suffix is ok.
