### ISSUE TITLE
Add Flex features to list

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs-validator#1776]
### Describe the problem

[Now that Flex is adopted](https://github.com/google/transit/pull/433), we want to be able to track usage of Flex features within the validator and within the Mobility Database API, [which includes features generated by the GTFS Schedule Validator.](https://mobilitydata.github.io/mobility-feed-api/SwaggerUI/index.html#/datasets/getDatasetGtfs)

### Proposed solution

The following four features should be added: 

Booking Rules: At least one record in booking_rules.txt
Fixed-Stops Demand Responsive Transit: At least one record in location_groups.txt
Zone-based Demand Responsive Transit: At least a trip in stop_times references only location_id 
Deviated Fixed Route: At least a trip in stop_times references location_id AND stop_id AND arrival_time AND departure_time

**Comment by emmambd** [comment]
cc @Sergiodero @tzujenchanmbd

**Comment by tzujenchanmbd** [comment]
I'd like to modify Deviated Fixed Route a bit:
At least a trip in stop_times references location_id AND stop_id AND arrival_time AND departure_time

**Comment by qcdyx** [comment]
@emmambd Could you elaborate on the definition of Zone-based Demand Responsive Transit?

In the first screenshot, each trip_id corresponds to a location_id. Is this a valid example? (I believe yes)
What might constitute an invalid example? 
<img width="1184" alt="image" src="https://github.com/MobilityData/gtfs-validator/assets/5789435/c4f53f13-ac63-4e5f-ab88-b0a236932f94">
Is the second screenshot an invalid Zone-based Demand Responsive Transit? (yes, since it contains a_valid_stop_id)
<img width="1185" alt="image" src="https://github.com/MobilityData/gtfs-validator/assets/5789435/67a21007-77e5-4c40-a456-f525871df92d">

**Comment by emmambd** [comment]
@qcdyx You're correct - Zone-based Demand Responsive Transit should be triggered when there is a location_id associated with a trip_id. It should not be triggered when stop_id is associated with trip_id. 

So the logic is: **if the trip has a location_id and NO stop_id, trigger Zone-based Demand DRT**

make sense?
