### ISSUE TITLE
Compare average processing time for validator between 5.0 and 6.0

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs-validator#1876]
### Describe the problem

In order to be confident that [the new column additions to stop_times.txt](#1749) with Flex are not having a significant impact on the validator's performance, we want to compare the average runtime for the validation between 5.0 and 6.0.

### Proposed solution

Include analytics about how long run time was in 5.0 vs. 6.0 for each feed.

**Comment by davidgamez** [comment]
## Method
How the running time was extracted:
- Restored the beach _feat/1698_ base branch of #1771. In this PR, the time validationTimeSeconds was introduced to the JSON report. There were no significant changes from 5.0.1 to this branch.
- Created a PR with a branch based from _feat/1698_ to gather all JSON reports that includes the new field validationTimeSeconds. This PR had to be against a similar branch due to a limitation in GitHub that blocks automation to run when conflicts are present, [more info](https://github.com/orgs/community/discussions/26304).
- Created a Python script locally to compare metrics of the latest master acceptance tests with the one extracted from _feat/1698_(close to 5.0.1). The script also looks for the most significant changes in time consumption across all feeds.
- The Java memory max heap was increased to 12GB to avoid impacting the metrics due to crashing validators.

## Results

### Time performance metrics 
| Metric      | 5.0.1                                                                 | Master                                                               | Difference                           |
|-------------|-----------------------------------------------------------------------|----------------------------------------------------------------------|--------------------------------------|
| Average     | 3.93                                                                  | 4.04                                                                 | 0.11                                 |
| Median      | 1.38                                                                  | 1.43                                                                 | 0.05                                 |
| Std Dev     | 11.07                                                                 | 11.55                                                                | 0.48                                 |
| Min         | feed_id: us-florida-citrus-county-transit-gtfs-630, time: 0.517 | feed_id: us-oregon-high-desert-point-gtfs-636, time: 0.540      | 0.023                          |
| Max         | feed_id: gb-unknown-uk-aggregate-feed-gtfs-2014, time: 289.510  | feed_id: gb-unknown-uk-aggregate-feed-gtfs-2014, time: 298.620  | 9.110                          |

** All values are expressed in seconds

There is a minor increase in the metrics but not a significant increase.

### Feeds with the most significant increase
In the following chart, there is a list of the most significant changes in time filter out all the changes less than 5 seconds to reduce noise.

![Image](https://github.com/user-attachments/assets/3a0b0b35-83e2-456b-b3e1-a31f42b3bb17)

Only six feeds differed by more than 5 seconds, and one of them reduced time.
