### ISSUE TITLE
[REQUEST] Implement stop time pickup and drop off types verification

### ISSUE THREAD

**Issue by maximearmstrong** [MobilityData/gtfs-validator#199]
**Is your feature request related to a problem? Please describe.**
A stop time should have valid pickup and drop off types. A stop should allowed riders at least one or the other : to get in or to get out at a stop. This is a GTFS rule implemented in Google Python validator as an inner verification in StopTimes __init__.

**Describe the solution you'd like**
Actual Google GTFS validator behaviour : verifies if pickup and drop off types are valid, and if they are not both set to 1 (1 = rider can't get in or out here)
https://github.com/google/transitfeed/blob/d727e97cb66ac2ca2d699a382ea1d449ee26c2a1/transitfeed/stoptime.py#L113

**Describe alternatives you've considered**

**Additional context**
Line 186 in Error support priorities https://docs.google.com/spreadsheets/d/1vqe6wq7ctqk1EhYkgtZ0_TbcQ91vccfs2daSjn20BLE/edit#gid=0

**Comment by barbeau** [comment]
cc @timMillet 

I believe this is another rule where GTFS industry practices have change since this rule was implemented. I don't see any mention in GTFS spec that says a stop can't have pickup and dropoff types both set to 1:
* https://gtfs.org/reference/static#stop_timestxt

And actually the [best practices](https://gtfs.org/best-practices/#stop_timestxt) say:

>* Non-revenue (deadhead) trips that do not provide passenger service should be marked with pickup_type and drop_off_type value of 1 for all stop_times rows.
>* On revenue trips, internal “timing points” for monitoring operational performance and other places such as garages that a passenger cannot board should be marked with pickup_type = 1 (no pickup available) and drop_off_type = 1 (no drop off available).

Although the exact error in the Python validator [says](https://github.com/google/transitfeed/blob/d727e97cb66ac2ca2d699a382ea1d449ee26c2a1/transitfeed/stoptime.py#L120):

>'This stop time has a pickup_type and '
                            'drop_off_type of 1, indicating that riders '
                            'can\'t get on or off here.  Since it doesn\'t '
                            'define a timepoint either, this entry serves no '
                            'purpose and should be excluded from the trip.',
                            type=problems_module.TYPE_WARNING)

So it sounds like the Python rule is actually referencing the 2nd bullet - the rule being "if a stop isn't a timepoint and it has both dropoff and pickup type = 1 then it's an error". But this doesn't take into account non-revenue trips as defined in the first bullet.

So maybe the updated rule should be:

>"if a stop isn't a timepoint AND
it has both dropoff and pickup type = 1 AND
at least one stop in the trip doesn't have pickup and dropoff type = 1
then it's an error"

**Comment by lionel-nj** [comment]
Implemented in https://github.com/MobilityData/gtfs-validator/pull/88
