### ISSUE TITLE
Keeping validator up-to-date with the spec

### ISSUE THREAD

**Issue by lionel-nj** [MobilityData/gtfs-validator#311]
**Is your feature request related to a problem? Please describe.**
Newly integrated extensions to the GTFS spec makes it mandatory to update our representation of GTFS entities. In this case, `Route` entities should be updated with the following fields:
- `continuous_drop_off`
- `continuous_pickup`

**Describe the solution you'd like**
- Add new fields to `GTFS entity`
- Verify enum values
- update tests

**Comment by e-lo** [comment]
Suggest at the very least add a cron job to auto-generate an issue when a PR for google/transit is merged to master so that we know each time something is changed.

IMO I would appreciate a solution that:
1. Syncs the [gtfs_spec.asciipb](https://github.com/MobilityData/gtfs-validator/blob/ddfa8e75cf34859188eecbf6269114bf8cba2845/adapter/repository/in-memory-simple/src/main/resources/gtfs_spec.asciipb) with "something" ([TBD? let's push this?](https://github.com/google/transit/issues/127)) on the official [google/transit repo](https://github.com/google/transit) via an auto-generated PR. 
2. Auto-generate an issue to review if additional rules need to be added using instructions on [ADDING_NEW_RULES.md](https://github.com/MobilityData/gtfs-validator/blob/master/ADDING_NEW_RULES.md). 
3. Tests using the reference dataset where the new GTFS spec was implemented.

**Comment by fabrice-v** [comment]
Hi,

Thks for the suggestion. Would you have any pointer as to technological solutions, examples, how to, guides or anything help that could help shape a solution? Preferably FOOS.

**Comment by e-lo** [comment]
> Would you have any pointer as to technological solutions, examples, how to, guides or anything that could help shape a solution?

[dependabot](https://dependabot.com/java/) comes to mind but is for "dependencies". 

There are lots of GH Workflows for generating [issues](https://github.com/JasonEtco/create-an-issue) and [PRs](https://stackoverflow.com/questions/57503578/making-pull-requests-to-a-github-repository-automatically-with-github-actions?rq=1) – I bet you can trigger them from within the Docker container by running a git command diffing the specification files and checking for differences.

**Comment by isabelle-dr** [comment]
Created [this issue](https://github.com/MobilityData/gtfs-validator/issues/911) for validation on continuous pickup and dropoff, keeping this one open for discussions around keeping the validator up-to-date with the spec

**Comment by isabelle-dr** [comment]
Closing this issue, as we opened [a project](https://mobilitydata.productboard.com/portal/3-gtfs-extensions/tabs/bd153f45-30c2-44f7-95e2-9e06933c2bf7/features/5523616/portal/expanded) that will cover this issue.
