### ISSUE TITLE
[BUG] validation error for extraneous blank rows

### ISSUE THREAD

**Issue by mcplanner** [MobilityData/gtfs-validator#402]
**Describe the bug**
A file has blank rows after its content, and is rendering a validation error for "invalid row length".

**To Reproduce**
Run on this file: https://realtime.goldengate.org/gtfsstatic/GTFSTransitData.zip

**Expected behavior**
I don't expect empty rows after the body of the content to create a validation error.

**Witnessed behavior**
`Notice{filename='fare_rules.txt', level='ERROR', code='4', title='Invalid row length', description='Invalid length for row:52 -- expected:5 actual:1', extra='{actualLength=1, rowIndex=52, expectedLength=5}'}, `

**Environment used**
- OS: macOS Catalina 10.15.6
- Java version: 11.0.5
- gtfs-validator version: gtfs-validator-v1.3.0-SNAPSHOT.jar

**Additional context**
The file is not using agency_ID properly, so v1.3.0 is necessary.

**Comment by mcplanner** [comment]
I believe this is also the cause of the complementary error:

`Notice{filename='fare_rules.txt', level='ERROR', code='15', title='Missing required value', description='Missing value for field:`fare_id` marked as required in entity with id:`null`', extra='{fieldName=fare_id}'}, `

**Comment by fabrice-v** [comment]
After analysis, it appears the rows in the provided dataset file are not empty.

An empty row shall contain the right number of comas to define as many empty values as there are headers in the first row.
What we found in the provided dataset are malformed rows:
![image](https://user-images.githubusercontent.com/55884852/95998231-aa9be900-0e02-11eb-85c1-7c9088dd9178.png)


As such, the validator works as intended by flagging malformed CSV rows in the input data.

Note that the behavior of the validator is undefined after the first error, which is why it runs with `abort_on_error` by default.
