### ISSUE TITLE
[REQUEST] Add functional tests to testing suite 

### ISSUE THREAD

**Issue by e-lo** [MobilityData/gtfs-validator#405]
**Is your feature request related to a problem? Please describe.**
As a local user, I would appreciate end-to-end functional tests be included in *repository* testing suite (as opposed to in a GitHub-triggered-action) in order to make sure the code *in my environment* is working appropriately from end-to-end. 

**Describe the solution you'd like**
A set of end-to-end functional tests for a variety of feed sources and settings run within local tests. 
https://guides.gradle.org/testing-gradle-plugins/ has some suggestions. 

**Describe alternatives you've considered**
While the GitHub triggered functional test is useful, it is not easily run locally by non-contributors *and* isn't necessarily run as a matter of course on local machines prior to pushing code.

**Comment by fabrice-v** [comment]
> https://guides.gradle.org/testing-gradle-plugins/ has some suggestions.

"In this guide you will learn effective techniques for testing plugin code."

Given we are not developing a Gradle plugin the specifics are far from applicable directly. We understand and share the insights about testing in general.

After analyzing your request, we came up with the following

On some other PRs, it was brought to our attention that running the validator locally is not ideal and providing Docker images would help in that regard. We foresee two possible path forward

1. leverage our GitHub actions and provide a way to run them locally in Docker
2. add a shell script to the Docker image that would loop through a set of URLs and invoke the validator. It would work by having the script in the repository and copying it in the image via the `Dockerfile`. The script would be invoked via CLI once logged into the running container.

Working on `1` is planned for the current sprint while we work on implementing an extra layer of CI see #416

Would that be in line with what you have in mind?

**Comment by e-lo** [comment]
> specifics are far from applicable directly

Sorry I didn't supply anything directly useful 🙃 I usually deal with 🐍 and fully admit I don't know my way around ☕ 

I think the shell script (or a script for whatever the appropriate way to do functional tests is in Java) is fine and would serve the purpose so long as it meets these criteria:

A. I shouldn't have to be in the Docker image to run the tests locally
B. It should be run when executing whatever testing directions are in the readme and in CI when evaluating PRs

**Comment by fabrice-v** [comment]
Ok I think I get a clearer picture.

It is our intention to focus on unit testing as we don't foresee a situation where a dataset 'breaking' the code (either directly by crashing it or indirectly by generating a non sensical report) could not be translated into a suite of unit tests. The suite of tests would become the non ambiguous version of the spec. Unit tests could also be developed while new extensions are developed as a way to flush out any ambiguity coming from natural language before adoption.

For end to end testing (which is almost equivalent in our cli case because we don't have a complex interface nor do we integrate with external resources and services), we certainly don't have the capacity to provide support for potential local configuration issues. Both in terms of reproducing the issues as well as provide help to fix them.

In consequence, the best we can presently do is provide support for a replicable environment like the one proposed by Docker or GitHub actions.
We will actually provide guidance and support on [how to fork the repository](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) and run the validator on any number of public datasets by modifying the end_to_end GitHub workflow, without needing anything else than a GitHub account. 
In case of an incorrect behavior of the validator, PRs could then be opened in which failing unit tests covering the issue could be developed in collaboration with the requester. That way, as time goes the number of datasets and configurations tests in the end to end workflow could be extended in a collaborative manner.
Advanced users needs would be served by allowing them to run those GitHub actions locally within Docker.

Because this workflow can potentially consume a lot of resources and take a lot of time to execute, we're still evaluating the best way/frequency to run it. At a minimum it will run for every commit on the master branch.

Hope that answer some of your questions, thks for your feedback and bearing with us while we progress towards something that could hopefully fit your needs within our constraints

**Comment by e-lo** [comment]
-  Agree that running a bunch of feeds of varying quality/complexity (@mcplanner can provide some) via a shell script should be fine. 
- I'm just asking that the shell script sit in a `/bin` `/scripts` etc. folder in the repo rather than embedded in docker (no objection to you then running it in docker)
- I think it is totally valid to caveat the instructions about how to run the shell script with tests with a disclaimer like "feel free to submit an issue about your local setup not working, but we will prioritize supporting the docker environment"
- master branch or running on PRs makes sense to me

**Comment by fabrice-v** [comment]
> I'm just asking that the shell script sit in a /bin /scripts etc. folder in the repo rather than embedded in docker (no objection to you then running it in docker)

Yes that what was envisioned with the script sitting in the repo and being copied over to the image the same way the jar is, see https://github.com/MobilityData/gtfs-validator/blob/f3e1ab91c966a298306bf42dbb67049408ed040e/Dockerfile#L3

That being said, having such a script would be separate from the GitHub workflow, hence both would need to be synchronised, which is not ideal. We keep it in mind.

**Comment by fabrice-v** [comment]
@e-lo FYI, we integrated the dataset provided in #399 against which future merges on master will be tested.
https://github.com/MobilityData/gtfs-validator/runs/1276757003?check_suite_focus=true

**Comment by fabrice-v** [comment]
@e-lo FYI, we integrated the dataset provided in #398 as fixing the original issue revealed a bug within our implementation. 
https://github.com/MobilityData/gtfs-validator/runs/1277644807?check_suite_focus=true

**Comment by fabrice-v** [comment]
@e-lo In the end we provide a script located in the repository that is also copied over to the Docker image.
It can be used at your convenience to automate running the validator in your local environment. As mentioned we will not provide any kind of support for it at this stage.

Thks for your input!

**Comment by fabrice-v** [comment]
FYI, this is now available and here is the relevant section in the documentation
https://github.com/MobilityData/gtfs-validator/blob/master/README.md#prerequisites

> Note: As a convenience, a shell script file is provided in the same directory. It is copied from end_to_end.sh It can be used to run the validator in an automated way. Only community based support is provided for local runs of the validator.

Once again, thks for your contributions, they help refine our processes and way of collaborating!
