### ISSUE TITLE
New docker image is using debian version that's past its end-of-life

### ISSUE THREAD

**Issue by machow** [MobilityData/gtfs-validator#844]
## **Bug report** 

Hey, thanks for your work on this project. This is overall a very small issue, but I figured I'd raise in case it's useful :).

**Describe the bug**

For v2.0.0, the Dockerfile moved from building on Debian 10 to Debian 8 (jesse).
However, [Debian 8's end-of-life was June 30, 2020](https://www.debian.org/News/2020/20200709).

This makes the image a bit tricky to extend, since [commands like apt-get update fail](https://superuser.com/questions/1417617/apt-get-update-is-failing-in-debian) without some finagling with the sources.

**How we reproduce the bug**

Build the v1.4.0 image and the v2.0.0 images. Inside the containers, run...

```
cat /etc/issue
```

To see the Debian version.

**Expected behaviour**

v2.0.0 container using debian 9 or 10.

**Observed behaviour**

v2.0.0 container using debian 8

**Comment by barbeau** [comment]
I'm not a Docker expert, but I'm guessing it's because the Docker image switched from using `FROM openjdk:11` to `FROM java:8` in v2, and the Java 8 image must use Debian 8?

AFAIK there shouldn't be anything blocking v2 from switching to using `FROM openjdk:11` again in the Dockerfile, if that will fix the issue - it should run fine on Java 11.

**Comment by lionel-nj** [comment]
Hi @machow! Thanks for flagging this! We'll make sure to take your feedback into consideration when planning work for the next sprints (@carlfredl).

**Comment by lionel-nj** [comment]
@machow the next release of the gtfs-validator will be using Debian 10 for the docker image. See #891.
