### ISSUE TITLE
[BUG] - Protobuf export crashes

### ISSUE THREAD

**Issue by fabrice-v** [MobilityData/gtfs-validator#86]
**Describe the bug**
Trying to generate protobuf export of validation results leads to a crash when processing MTBA dataset.

**To Reproduce**
Launch the app with the following parameters `-u https://transitfeeds.com/p/mbta/64/latest/download -z input.zip -i input -o output -p`

**Expected behavior**
A collection of protobuf files should be placed in the output folder

**Witnessed behavior**
A NullPointerException is raised in the ProtobufExporter object

**Screenshots**
entityId filed in notice object is null
![image](https://user-images.githubusercontent.com/55884852/77657258-6e2e9b80-6f4b-11ea-9d78-7ec601c8eb32.png)

 
**Additional context**
It should not be possible to create a notice with a null entity ID, this construction parameter needs to be annotated

**Comment by lionel-nj** [comment]
Working on this

**Comment by lionel-nj** [comment]
From what I witnessed:

-as stated by @fabrice-v  we should not be able to create a notice with a null entity Id -> use annotations for parameters that are get from getEntityId method

-files like transfers.txt do not have entityId, so when getEntityId is called it returns null. For this case, I suggest to modify the relevant notices constructor with 
`this.entityId = entityId != null ? entityId:"no id";` so that this field is not passes with null value
