### ISSUE TITLE
Suggestion: make UnexpectedEnumValueNotice an error instead of a warning

### ISSUE THREAD

**Issue by mcplanner** [MobilityData/gtfs-validator#903]
**What problem in GTFS datasets does this new rule address? Please describe.**
UnexpectedEnumValueNotice is currently categorized as a warning, but flags inconsistent with the GTFS spec, which should make it an error.

**Comment by barbeau** [comment]
There is some unofficial history of allowing producers to extend GTFS by using their own enumeration values that aren't listed in the spec. One past example that is likely still in use somewhere in the world is Google's "Extended GTFS Route Types":
https://developers.google.com/transit/gtfs/reference/extended-route-types

IMHO this needs to be clarified in the spec itself - whether extending enumerations is currently allowed (and if so, for which fields, if we want to restrict this by field). If yes, then this should continue to be a WARNING. If no, then this should be changed to an ERROR.

**Comment by isabelle-dr** [comment]
Ruth, thank you for opening this. I decided to close this issue, as this Notice will stay a WARNING severity level for now in order to not introduce breaking changes to the datasets that use additional enum values. 

This might change if Google's extended route types get added in the specification (conversation about it [here](https://github.com/MobilityData/gtfs-validator/issues/927)). 
If this happens, we can re-assess if having this Notice an ERROR would still introduce a breaking change and if it doesn't, I think that would make sense to have this as an ERROR
