### ISSUE TITLE
Modify resultRepo to adopt a streaming model

### ISSUE THREAD

**Issue by ghost** [MobilityData/gtfs-validator#94]
**Is your feature request related to a problem? Please describe.**
Right now, validation result exportation happens at the end of the applicaiton execution. As such, all notices are kept in memory and may potentially consume all of it. This PR work consist in modifying the in memory implementation to adopt a streaming model for notices export.

**Describe the solution you'd like**
Current JSON exporting already uses a streaming output JsonGenerator. As such, modifications should be minimal. Two leads
- Have a new export use case ran regularly during in the main method execution
- Have the repository itself pipe calls to its add methods to the exporter object

Both should be explored and this issue updated with the results before proceeding to implementation.

**Additional context**
https://github.com/MobilityData/gtfs-validator/issues/77

**Comment by fabrice-v** [comment]
After discussion, the repository should abstract the export process through the use of an internal Exporter member. No specific use case should be used.

**Comment by lionel-nj** [comment]
After discussion
- https://github.com/MobilityData/gtfs-validator/issues/94#issuecomment-607495789
- At present, a first attempt to implement the export behavior directly in the add methods could be possible. However, doing so leads us to loose the "single responsability principle " for these add methods.

Note: For now, using a thread to execute a use case to regularly export the notices is not possible.

**Comment by maximearmstrong** [comment]
I suggest we use the [Observer pattern](https://www.baeldung.com/java-observer-pattern) from the [Design patterns ](https://github.com/TushaarGVS/Design-Patterns-Mentorship/blob/master/Erich%20Gamma%2C%20Richard%20Helm%2C%20Ralph%20Johnson%2C%20John%20M.%20Vlissides-Design%20Patterns_%20Elements%20of%20Reusable%20Object-Oriented%20Software%20%20-Addison-Wesley%20Professional%20(1994).pdf). `ValidationResultRepository` would be observable, and an exporter object would be the observer. Every time an add method is triggered in `ValidationResultRepository`, a signal is sent to the exporter object. In this case, `ValidationResultRepository` methods would not break the "single responsibility principle" because they would only send a signal.

**Comment by lionel-nj** [comment]
Good catch, Taking a look at this

**Comment by lionel-nj** [comment]
After discussion (last week), it came up that the Observer API has been deprecated, so the Flow API could be used instead: https://docs.oracle.com/javase/9/docs/api/java/util/concurrent/Flow.Publisher.html

**Comment by barbeau** [comment]
Closing - addressed in v2 architecture
